<?php
/**
 * InstanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationServer
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Server API
 *
 * Bumbal Communication Server API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalCommunicationServer;

use \BumbalCommunicationServer\Configuration;
use \BumbalCommunicationServer\ApiClient;
use \BumbalCommunicationServer\ApiException;
use \BumbalCommunicationServer\ObjectSerializer;

/**
 * InstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalCommunicationServer
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createInstance
     *
     * Create a Instance.
     *
     */
    public function testCreateInstance()
    {

    }

    /**
     * Test case for deleteInstance
     *
     * Delete a Instance.
     *
     */
    public function testDeleteInstance()
    {

    }

    /**
     * Test case for retrieveInstance
     *
     * Retrieve a Instance.
     *
     */
    public function testRetrieveInstance()
    {

    }

    /**
     * Test case for retrieveListInstance
     *
     * Retrieve List of Instances.
     *
     */
    public function testRetrieveListInstance()
    {

    }

    /**
     * Test case for updateInstance
     *
     * Update an Instance.
     *
     */
    public function testUpdateInstance()
    {

    }

}
