<?php
/**
 * InstanceModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Server API
 *
 * Bumbal Communication Server API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalCommunicationServer;

/**
 * InstanceModelTest Class Doc Comment
 *
 * @category    Class */
// * @description InstanceModel
/**
 * @package     BumbalCommunicationServer
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InstanceModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InstanceModel"
     */
    public function testInstanceModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "domain_name"
     */
    public function testPropertyDomainName()
    {
    }

    /**
     * Test attribute "api_key"
     */
    public function testPropertyApiKey()
    {
    }

    /**
     * Test attribute "suppressed"
     */
    public function testPropertySuppressed()
    {
    }
}
