<?php
/**
 * InstanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Server API
 *
 * Bumbal Communication Server API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalCommunicationServer;

use \BumbalCommunicationServer\Configuration;
use \BumbalCommunicationServer\ApiClient;
use \BumbalCommunicationServer\ApiException;
use \BumbalCommunicationServer\ObjectSerializer;

/**
 * InstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalCommunicationServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InstanceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createInstance
     *
     * Create a Instance.
     *
     */
    public function testCreateInstance()
    {
    }

    /**
     * Test case for deleteInstance
     *
     * Delete a Instance.
     *
     */
    public function testDeleteInstance()
    {
    }

    /**
     * Test case for purgeInstance
     *
     * Purge data for an Instance.
     *
     */
    public function testPurgeInstance()
    {
    }

    /**
     * Test case for purgeInstanceByName
     *
     * Purge data for an Instance by instance Name.
     *
     */
    public function testPurgeInstanceByName()
    {
    }

    /**
     * Test case for retrieveInstance
     *
     * Retrieve a Instance.
     *
     */
    public function testRetrieveInstance()
    {
    }

    /**
     * Test case for retrieveListInstance
     *
     * Retrieve List of Instances.
     *
     */
    public function testRetrieveListInstance()
    {
    }

    /**
     * Test case for updateInstance
     *
     * Update an Instance.
     *
     */
    public function testUpdateInstance()
    {
    }
}
