<?php
/**
 * LogsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalCommunicationServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Communication Server API
 *
 * Bumbal Communication Server API documentation
 *
 * OpenAPI spec version: 1.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalCommunicationServer;

use \BumbalCommunicationServer\Configuration;
use \BumbalCommunicationServer\ApiClient;
use \BumbalCommunicationServer\ApiException;
use \BumbalCommunicationServer\ObjectSerializer;

/**
 * LogsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalCommunicationServer
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LogsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for retrieveListLog
     *
     * Retrieve List of Activities.
     *
     */
    public function testRetrieveListLog()
    {
    }

    /**
     * Test case for retrieveLog
     *
     * Retrieve a log entry.
     *
     */
    public function testRetrieveLog()
    {
    }

    /**
     * Test case for truncateLog
     *
     * Truncate Log Table.
     *
     */
    public function testTruncateLog()
    {
    }
}
